version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.nginx
    ports:
      - "${PORT}:80"
    depends_on:
      - php
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  php:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.php
    environment:
      API_SERVER_HOST: $API_SERVER_HOST
      API_SERVER_PORT: $API_SERVER_PORT
    volumes:
      - ./src:/var/www/html
